version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:latest
    ports:
      - '4566-4597:4566-4597'
    environment:
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d/
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"